CREATE TABLE Guardian
(
  id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX Username ON Guardian (username);

CREATE TABLE device
(
  Id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL
);

CREATE TABLE DeviceData
(
  Id INT(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  DeviceID INT(11) NOT NULL,
  DataTime DATETIME NOT NULL,
  Longitude FLOAT(10,6),
  Latitude FLOAT(10,6),
  HeartRate DOUBLE,
  CONSTRAINT FOREIGN KEY (DeviceID) REFERENCES device (Id)
);

CREATE TABLE Device_Guardian
(
  GuardianId INT(11) NOT NULL,
  DeviceId INT(11) NOT NULL,
  CONSTRAINT `PRIMARY` PRIMARY KEY (GuardianId, DeviceId),
  CONSTRAINT  FOREIGN KEY (GuardianId) REFERENCES Guardian(id),
  CONSTRAINT  FOREIGN KEY (DeviceId) REFERENCES device (Id)
);
